### ISSUE TITLE
thanks for your update

### ISSUE THREAD

**Issue by supmyhava** [akasakaid/gameetod#17]
hi mate thanks for your update!
btw the bot using race ? and upgrade mining ?

**Comment by akasakaid** [comment]
> hi mate thanks for your update! btw the bot using race ? and upgrade mining ?

Sorry for that, for now my computer can't run the “race” feature because my computer doesn't support it. 
I've actually written that in the readme only I put a comment so it doesn't show the writing about there is no “race” feature, maybe you can check it yourself for more detailed reasons I didn't add the feature.
